acqs_models:
  - "random rwll"
  - "unc rwll"
  - "uncnorm rwll"
  - "uncnormdecaytau rwll"

acc_models:
  - "rwll"

seeds: [2, 3, 5]

representation:
  type: nn
  random_seed: 0

  nn_name: mlp
  nn_layer: 4
  nn_hidden_dim: 128
  nn_num_hidden_layers: 4
  nn_epochs: 30
  nn_batch_size: 64
  nn_lr: 0.001

initial_labels_per_class: 1